version: "3.9"

services:
  app:
    build:
      dockerfile: dockerfile
      context: .
    container_name: praktyki-project
    working_dir: /app
    environment:
      - CONN_STR=mongodb://root:Start1234@mongodb:27017
    volumes:
      - ./:/app
    ports:
      - 3000:5555
    command: "npm start"
#    command: tail -f /dev/null
    depends_on:
      - mongodb
  mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=Start1234
      - MONGO_INITDB_DATABASE=shop
    volumes:
      - ./json:/docker-entrypoint-initdb.d
      - mongoData:/data/db

volumes:
  mongoData: